"""The MCP backend as containers, on the remote machine.

What can and cannot be containerized — this determines the whole design:

  * **Premiere Pro cannot.** It is a licensed macOS GUI app. It stays on the
    host, and so does the CEP panel it loads.
  * **The CEP WebSocket (9801) is on the host.** Anything that talks to the
    panel must reach the host, which from a container means
    `host.docker.internal`.
  * **rust-engine and python-intelligence containerize cleanly** — they only
    touch media files and gRPC. Upstream already ships these in compose.
  * **go-orchestrator is an MCP *stdio* server.** A client launches it and
    speaks over stdin/stdout, which does not fit a long-running service. We run
    it as a container that stays up for gRPC/health, and expose a
    `docker run -i` invocation for stdio clients.

Note the CLI itself does not need any of this: umcares drives Premiere through
the CEP DevTools port directly, precisely because the MCP tool layer is broken.
The stack is for reproducible media analysis and for serving other MCP clients.

Compose runs ON THE REMOTE, because that is where both the media and the host
CEP socket live.
"""
from __future__ import annotations

import json
import shlex

from . import log
from .config import Remote
from .transport import Transport

OVERRIDE_NAME = "docker-compose.umcares.yml"

# Adds the two services upstream deliberately leaves on the host, wired so they
# can still reach the CEP panel through host.docker.internal.
OVERRIDE_YML = """# Generated by umcares. Adds the Go orchestrator and TS bridge to the
# upstream compose file. Premiere and the CEP panel remain on the host; the
# bridge reaches them via host.docker.internal.
services:
  ts-bridge:
    build:
      context: .
      dockerfile: Dockerfile
      target: node-runtime
    command: node --import tsx src/index.ts
    working_dir: /app/ts-bridge
    ports:
      - "127.0.0.1:50054:50054"
    environment:
      BRIDGE_GRPC_HOST: 0.0.0.0
      BRIDGE_GRPC_PORT: "50054"
      # the CEP panel's WebSocket server lives on the host, not in the network
      CEP_WS_URL: "ws://host.docker.internal:9801"
      MEDIA_ENGINE_ADDR: "rust-engine:50052"
      INTEL_ADDR: "python-intel:50053"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rust-engine
      - python-intel

  go-orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: go-runtime
    # stdio MCP clients should use:  docker compose run --rm -T go-orchestrator
    command: ["premierpro-mcp", "--health-addr", "0.0.0.0:8090"]
    ports:
      - "127.0.0.1:8090:8090"
    environment:
      MEDIA_ENGINE_ADDR: "rust-engine:50052"
      INTEL_ADDR: "python-intel:50053"
      BRIDGE_ADDR: "ts-bridge:50054"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rust-engine
      - python-intel
      - ts-bridge
"""


def _compose(remote: Remote, extra: str = "") -> str:
    """Compose invocation with both files and the media roots bound."""
    return (
        f"cd {shlex.quote(remote.mcp_repo)} && "
        f"PREMIERE_MEDIA_ROOT={shlex.quote(remote.root)} "
        f"PREMIERE_OUTPUT_ROOT={shlex.quote(remote.exports)} "
        f"docker compose -f docker-compose.yml -f {OVERRIDE_NAME} {extra}"
    )


def ensure_override(t: Transport, remote: Remote) -> None:
    """Write our override next to the upstream compose file."""
    import tempfile
    from pathlib import Path as _P
    with tempfile.NamedTemporaryFile("w", suffix=".yml", delete=False,
                                     encoding="utf-8") as fh:
        fh.write(OVERRIDE_YML)
        tmp = _P(fh.name)
    try:
        t.push(tmp, f"{remote.mcp_repo}/{OVERRIDE_NAME}")
    finally:
        tmp.unlink(missing_ok=True)


def preflight(t: Transport, remote: Remote) -> dict:
    script = f"""
echo "docker=$(command -v docker >/dev/null && docker --version || echo missing)"
docker info >/dev/null 2>&1 && echo "daemon=up" || echo "daemon=down"
echo "compose=$(docker compose version --short 2>/dev/null || echo missing)"
test -f {shlex.quote(remote.mcp_repo)}/docker-compose.yml && echo "repo=ok" || echo "repo=missing"
test -f {shlex.quote(remote.mcp_repo)}/Dockerfile && echo "dockerfile=ok" || echo "dockerfile=missing"
"""
    r = t.run_script(script, timeout=180)
    info = {}
    for line in r.stdout.splitlines():
        if "=" in line and not line.startswith("port:"):
            k, v = line.strip().split("=", 1)
            info[k] = v

    # The host may already be running these services (scripts/start-all.sh).
    # Docker would then fail with an opaque "port is already allocated".
    conflicts = {}
    probe = t.run(
        "for p in 50052 50053 50054 8090; do "
        "  o=$(lsof -nP -iTCP:$p -sTCP:LISTEN 2>/dev/null | awk 'NR==2{print $1\" pid=\"$2}'); "
        "  [ -n \"$o\" ] && echo \"$p|$o\"; done", timeout=120)
    for line in probe.stdout.splitlines():
        if "|" in line:
            port, owner = line.strip().split("|", 1)
            if "docker" not in owner.lower() and "com.docke" not in owner.lower():
                conflicts[port] = owner
    info["host_port_conflicts"] = conflicts

    info["ok"] = (info.get("daemon") == "up" and info.get("repo") == "ok"
                  and info.get("dockerfile") == "ok")
    return info


def stop_host_services(t: Transport, remote: Remote) -> dict:
    """Stop the host-run backends so the containers can bind their ports."""
    r = t.run(f"cd {shlex.quote(remote.mcp_repo)} && ./scripts/stop-all.sh 2>&1 | tail -5",
              timeout=300)
    return {"ok": r.ok, "output": (r.stdout or r.stderr).strip()[-300:]}


def up(t: Transport, remote: Remote, build: bool = False,
      services: list | None = None, timeout: int = 3600,
      force: bool = False) -> dict:
    pre = preflight(t, remote)
    clash = pre.get("host_port_conflicts") or {}
    if clash and not force:
        detail = ", ".join(f"{p} ({o})" for p, o in sorted(clash.items()))
        raise RuntimeError(
            f"these ports are already held by host processes: {detail}\n"
            f"  the containers bind the same ports and would fail to start\n"
            f"  fix: `umcares stack up --stop-host` (runs scripts/stop-all.sh), "
            f"or stop them yourself")
    ensure_override(t, remote)
    what = " ".join(services or [])
    flags = "up -d" + (" --build" if build else "")
    r = t.run(_compose(remote, f"{flags} {what}"), timeout=timeout)
    if not r.ok:
        raise RuntimeError(f"compose up failed: {(r.stderr or r.stdout).strip()[-500:]}")
    return status(t, remote)


def down(t: Transport, remote: Remote, volumes: bool = False) -> dict:
    r = t.run(_compose(remote, "down" + (" -v" if volumes else "")), timeout=600)
    return {"ok": r.ok, "output": (r.stdout or r.stderr).strip()[-400:]}


def status(t: Transport, remote: Remote) -> dict:
    r = t.run(_compose(remote, "ps --format json"), timeout=180)
    rows = []
    for line in r.stdout.splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        rows.append({"service": d.get("Service"), "state": d.get("State"),
                     "status": d.get("Status"), "ports": d.get("Publishers")})
    # gRPC ports are the real health signal, not just "container is running"
    probe = t.run(
        "for p in 50052 50053 50054 8090; do "
        "  (nc -z 127.0.0.1 $p 2>/dev/null && echo \"$p=open\") || echo \"$p=closed\"; "
        "done", timeout=120)
    ports = {}
    for line in probe.stdout.splitlines():
        if "=" in line:
            k, v = line.strip().split("=", 1)
            ports[k] = v
    return {"services": rows, "ports": ports,
            "running": sum(1 for s in rows if s.get("State") == "running")}


def logs(t: Transport, remote: Remote, service: str = "", tail: int = 60) -> str:
    what = service or ""
    r = t.run(_compose(remote, f"logs --tail {tail} --no-color {what}"), timeout=300)
    return (r.stdout or r.stderr).strip()


def stdio_hint(remote: Remote) -> str:
    """How an MCP client should launch the containerized Go server."""
    return (f"cd {remote.mcp_repo} && "
            f"docker compose -f docker-compose.yml -f {OVERRIDE_NAME} "
            f"run --rm -T go-orchestrator premierpro-mcp")
